# .github/workflows/ci.yml
name: Node.js CI

on:
  push:
    branches: [ "main" ]  # Ejecuta en cada push al branch main

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Puedes cambiar por la versión que quieras

    - name: Ejecutar Hello World
      run: node index.js
